alter table SAJET.SYS_CUST_REPORT add( REPORT_VN VARCHAR2(100));
alter table SAJET.SYS_CUST_REPORT_COLUMN add( FIELD_VN VARCHAR2(50));
alter table SAJET.SYS_CUST_REPORT_2D_FORMULA add( HEADTEXT_VN VARCHAR2(100));
alter table SAJET.SYS_CUST_REPORT_PARAM add( DESC_VN VARCHAR2(25));
alter table SAJET.SYS_CUST_REPORT_TYPE add( REPORT_TYPE_VN VARCHAR2(100));
alter table SAJET.SYS_CUST_REPORT_LINK add( LINK_VN VARCHAR2(100));
alter table SAJET.SYS_CUST_REPORT_USER_CONTROL add( LINK_VN VARCHAR2(100));

alter table SAJET.SYS_PROGRAM_FUN_NAME add( FUN_TYPE_VN VARCHAR2(25));
alter table SAJET.SYS_PROGRAM_FUN_NAME add( FUN_VN VARCHAR2(50));
alter table SAJET.SYS_PROGRAM_FUN_NAME add( FUN_DESC_VN VARCHAR2(150));
alter table SAJET.SYS_PROGRAM_NAME add( PROGRAM_VN VARCHAR2(25));

alter table SAJET.SYS_RC_SHEET add( SHEET_VN VARCHAR2(25));

