alter table SAJET.SYS_PROGRAM_FUN_NAME modify (FUN_TYPE_VN VARCHAR2(120));
alter table SAJET.SYS_PROGRAM_FUN_NAME modify (FUN_VN VARCHAR2(120));

Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Cấu hình hệ thống', FUN_VN='Nhà máy', FUN_DESC_VN='Nhà máy' Where Program='Data Center' and FUNCTION = 'Factory';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Cấu hình hệ thống', FUN_VN='Chuyền sản xuất', FUN_DESC_VN='Chuyền sản xuất' Where Program='Data Center' and FUNCTION = 'Production Line';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Cấu hình hệ thống', FUN_VN='Công đoạn', FUN_DESC_VN='Công đoạn' Where Program='Data Center' and FUNCTION = 'Stage';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Cấu hình hệ thống', FUN_VN='Công nghệ', FUN_DESC_VN='Công nghệ' Where Program='Data Center' and FUNCTION = 'Process';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Cấu hình hệ thống', FUN_VN='Trạm làm việc', FUN_DESC_VN='Trạm làm việc' Where Program='Data Center' and FUNCTION = 'Terminal';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Cấu hình hệ thống', FUN_VN='Thuộc tính', FUN_DESC_VN='Thuộc tính' Where Program='Data Center' and FUNCTION = 'CProperty';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Cấu hình hệ thống', FUN_VN='Mức độ ưu tiên', FUN_DESC_VN='Mức độ ưu tiên' Where Program='Data Center' and FUNCTION = 'PriorityLevel';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Cấu hình hệ thống', FUN_VN='Đơn vị', FUN_DESC_VN='Đơn vị' Where Program='Data Center' and FUNCTION = 'Unit';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Cấu hình hệ thống', FUN_VN='Chuyển đổi đơn vị', FUN_DESC_VN='Chuyển đổi đơn vị' Where Program='Data Center' and FUNCTION = 'UnitConvert';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Cấu hình hệ thống', FUN_VN='Tham số hệ thống', FUN_DESC_VN='Tham số hệ thống' Where Program='Data Center' and FUNCTION = 'CParam';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin sản phẩm', FUN_VN='Loại mã vật liệu', FUN_DESC_VN='Loại mã vật liệu' Where Program='Data Center' and FUNCTION = 'Part_Type';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin sản phẩm', FUN_VN='Mã vật liệu', FUN_DESC_VN='Mã vật liệu' Where Program='Data Center' and FUNCTION = 'RCPart';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin sản phẩm', FUN_VN='Danh mục vật liệu (PCS)', FUN_DESC_VN='Danh mục vật liệu (PCS)' Where Program='Data Center' and FUNCTION = 'Part Master';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin sản phẩm', FUN_VN='Quy trình sản xuất', FUN_DESC_VN='Quy trình sản xuất' Where Program='Data Center' and FUNCTION = 'Route';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin sản phẩm', FUN_VN='Thông số đóng gói', FUN_DESC_VN='Thông số đóng gói' Where Program='Data Center' and FUNCTION = 'Packing Spec.';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin sản phẩm', FUN_VN='Định nghĩa bộ quy tắc', FUN_DESC_VN='Định nghĩa bộ quy tắc' Where Program='Data Center' and FUNCTION = 'Rule Set Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin sản phẩm', FUN_VN='Quy trình sản xuất (PCS)', FUN_DESC_VN='Quy trình sản xuất (PCS)' Where Program='Data Center' and FUNCTION = 'RoutePCS';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin sản phẩm', FUN_VN='Thiết lập thẻ quy trình', FUN_DESC_VN='Thiết lập thẻ quy trình' Where Program='Data Center' and FUNCTION = 'Run Card Config';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin sản phẩm', FUN_VN='Định mức vật tư (BOM)', FUN_DESC_VN='Định mức vật tư (BOM)' Where Program='Data Center' and FUNCTION = 'BOM';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin sản phẩm', FUN_VN='Quy tắc số seri KPSN', FUN_DESC_VN='Quy tắc số seri KPSN' Where Program='Data Center' and FUNCTION = 'KPSN Rule';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin sản phẩm', FUN_VN='Model sản phẩm', FUN_DESC_VN='Model sản phẩm' Where Program='Data Center' and FUNCTION = 'Model';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin sản phẩm', FUN_VN='Gắn mã vật liệu với nhãn in', FUN_DESC_VN='Gắn mã vật liệu với nhãn in' Where Program='Data Center' and FUNCTION = 'LabelPart';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin sản phẩm', FUN_VN='Kế hoạch lấy mẫu mặc định', FUN_DESC_VN='Kế hoạch lấy mẫu mặc định' Where Program='Data Center' and FUNCTION = 'Sampling Plan Default';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý chất lượng', FUN_VN='Loại lỗi', FUN_DESC_VN='Loại lỗi' Where Program='Data Center' and FUNCTION = 'DefectType';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý chất lượng', FUN_VN='Nguyên nhân lỗi', FUN_DESC_VN='Nguyên nhân lỗi' Where Program='Data Center' and FUNCTION = 'Reason';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý chất lượng', FUN_VN='Hiện tượng lỗi', FUN_DESC_VN='Hiện tượng lỗi' Where Program='Data Center' and FUNCTION = 'Defect';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý chất lượng', FUN_VN='Phân loại trách nhiệm', FUN_DESC_VN='Phân loại trách nhiệm' Where Program='Data Center' and FUNCTION = 'Duty';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý chất lượng', FUN_VN='Kế hoạch lấy mẫu', FUN_DESC_VN='Kế hoạch lấy mẫu' Where Program='Data Center' and FUNCTION = 'Sampling Plan';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý chất lượng', FUN_VN='Quy tắc lấy mẫu', FUN_DESC_VN='Quy tắc lấy mẫu' Where Program='Data Center' and FUNCTION = 'Sampling Rule';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý chất lượng', FUN_VN='Hạng mục kiểm tra', FUN_DESC_VN='Hạng mục kiểm tra' Where Program='Data Center' and FUNCTION = 'Test Item';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý chất lượng', FUN_VN='Hạng mục kiểm tra sản phẩm', FUN_DESC_VN='Hạng mục kiểm tra sản phẩm' Where Program='Data Center' and FUNCTION = 'Production Test Item';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý chất lượng', FUN_VN='Kế hoạch lấy mẫu theo khách hàng', FUN_DESC_VN='Kế hoạch lấy mẫu theo khách hàng' Where Program='Data Center' and FUNCTION = 'QC Part Process Sampling Plan';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý chất lượng', FUN_VN='Mã giữ (Hold Code)', FUN_DESC_VN='Mã giữ (Hold Code)' Where Program='Data Center' and FUNCTION = 'HoldCode';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý chất lượng', FUN_VN='Cảnh báo quá hạn giữ hàng', FUN_DESC_VN='Cảnh báo quá hạn giữ hàng' Where Program='Data Center' and FUNCTION = 'HoldTimeAlert';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thành viên hệ thống', FUN_VN='Phòng ban', FUN_DESC_VN='Phòng ban' Where Program='Data Center' and FUNCTION = 'Department';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thành viên hệ thống', FUN_VN='Nhân viên', FUN_DESC_VN='Nhân viên' Where Program='Data Center' and FUNCTION = 'Employee';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thành viên hệ thống', FUN_VN='Vai trò', FUN_DESC_VN='Vai trò' Where Program='Data Center' and FUNCTION = 'Role';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thành viên hệ thống', FUN_VN='Khách hàng', FUN_DESC_VN='Khách hàng' Where Program='Data Center' and FUNCTION = 'Customer';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thành viên hệ thống', FUN_VN='Nhà cung cấp', FUN_DESC_VN='Nhà cung cấp' Where Program='Data Center' and FUNCTION = 'Vendor';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thành viên hệ thống', FUN_VN='Ca làm việc', FUN_DESC_VN='Ca làm việc' Where Program='Data Center' and FUNCTION = 'Shift';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thành viên hệ thống', FUN_VN='Duy trì nhân viên theo vai trò', FUN_DESC_VN='Duy trì nhân viên theo vai trò' Where Program='Data Center' and FUNCTION = 'Role Emp Maintain';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thành viên hệ thống', FUN_VN='Gán vai trò', FUN_DESC_VN='Gán vai trò' Where Program='Data Center' and FUNCTION = 'Role Assign';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết bị', FUN_VN='Loại máy', FUN_DESC_VN='Loại máy' Where Program='Data Center' and FUNCTION = 'Machine Type';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết bị', FUN_VN='Nhóm máy', FUN_DESC_VN='Nhóm máy' Where Program='Data Center' and FUNCTION = 'MachineGroup';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết bị', FUN_VN='Máy móc', FUN_DESC_VN='Máy móc' Where Program='Data Center' and FUNCTION = 'Machine';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết bị', FUN_VN='Trạng thái máy', FUN_DESC_VN='Trạng thái máy' Where Program='Data Center' and FUNCTION = 'Machine Status';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết bị', FUN_VN='Quy tắc chuyển trạng thái máy', FUN_DESC_VN='Quy tắc chuyển trạng thái máy' Where Program='Data Center' and FUNCTION = 'Machine Status Move';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết bị', FUN_VN='Lý do thay đổi trạng thái máy', FUN_DESC_VN='Lý do thay đổi trạng thái máy' Where Program='Data Center' and FUNCTION = 'Machine Status Reason';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết bị', FUN_VN='Quyền thao tác máy', FUN_DESC_VN='Quyền thao tác máy' Where Program='Data Center' and FUNCTION = 'MachineAuthority';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết bị', FUN_VN='Bảng kiểm tra máy', FUN_DESC_VN='Bảng kiểm tra máy' Where Program='Data Center' and FUNCTION = 'Machine Check List';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết bị', FUN_VN='Hàng đợi thông báo máy', FUN_DESC_VN='Hàng đợi thông báo máy' Where Program='Data Center' and FUNCTION = 'MachineMQ';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin công đoạn', FUN_VN='Hiện tượng lỗi công đoạn', FUN_DESC_VN='Hiện tượng lỗi công đoạn' Where Program='Data Center' and FUNCTION = 'RCProcessDefect';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin công đoạn', FUN_VN='Định nghĩa biểu mẫu công đoạn', FUN_DESC_VN='Định nghĩa biểu mẫu công đoạn' Where Program='Data Center' and FUNCTION = 'Process Sheet Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin công đoạn', FUN_VN='Quyền hạn nhân viên công đoạn', FUN_DESC_VN='Quyền hạn nhân viên công đoạn' Where Program='Data Center' and FUNCTION = 'AuthoritySet';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin công đoạn', FUN_VN='Kiểm soát thời gian công đoạn', FUN_DESC_VN='Kiểm soát thời gian công đoạn' Where Program='Data Center' and FUNCTION = 'Process Time';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin công đoạn', FUN_VN='Thông số công đoạn (theo mã vật liệu)', FUN_DESC_VN='Thông số công đoạn (theo mã vật liệu)' Where Program='Data Center' and FUNCTION = 'Process Paramter(Part No)';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thông tin công đoạn', FUN_VN='Vật tư công đoạn', FUN_DESC_VN='Vật tư công đoạn' Where Program='Data Center' and FUNCTION = 'Process Material';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Khác', FUN_VN='Thiết lập kho WIP', FUN_DESC_VN='Thiết lập kho WIP' Where Program='Data Center' and FUNCTION = 'WIPINV CONFIG';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quyền không FIFO', FUN_VN='Quyền không áp dụng FIFO', FUN_DESC_VN='Quyền không áp dụng FIFO' Where Program='Data Center' and FUNCTION = 'NonFifo';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Lệnh sản xuất', FUN_VN='Duy trì lệnh sản xuất', FUN_DESC_VN='Duy trì lệnh sản xuất' Where Program='W/O Manager' and FUNCTION = 'W/O Maintain';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Lệnh sản xuất', FUN_VN='Quản lý lệnh sản xuất (PCS)', FUN_DESC_VN='Quản lý lệnh sản xuất (PCS)' Where Program='W/O Manager' and FUNCTION = 'W/O Manager PCS';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Trạng thái lệnh', FUN_VN='Phát hành/Lưu hành', FUN_DESC_VN='Phát hành/Lưu hành' Where Program='W/O Manager' and FUNCTION = 'W/O Release';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Trạng thái lệnh', FUN_VN='Hoàn thành', FUN_DESC_VN='Hoàn thành' Where Program='W/O Manager' and FUNCTION = 'W/O Complete';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Trạng thái lệnh', FUN_VN='Tạm giữ', FUN_DESC_VN='Tạm giữ' Where Program='W/O Manager' and FUNCTION = 'W/O Hold';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Trạng thái lệnh', FUN_VN='Huỷ bỏ', FUN_DESC_VN='Huỷ bỏ' Where Program='W/O Manager' and FUNCTION = 'W/O Cancel';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Trạng thái lệnh', FUN_VN='Phục hồi sau tạm giữ', FUN_DESC_VN='Phục hồi sau tạm giữ' Where Program='W/O Manager' and FUNCTION = 'W/O Resume';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Lệnh sản xuất', FUN_VN='Thuộc tính lệnh sản xuất', FUN_DESC_VN='Thuộc tính lệnh sản xuất' Where Program='W/O Manager' and FUNCTION = 'W/O Property';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập', FUN_VN='Thiết lập', FUN_DESC_VN='Thiết lập' Where Program='Barcode Center' and FUNCTION = 'Config';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhãn', FUN_VN='Nhãn số seri sản xuất', FUN_DESC_VN='Nhãn số seri sản xuất' Where Program='Barcode Center' and FUNCTION = 'S/N Label';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhãn', FUN_VN='Nhãn số seri khách hàng', FUN_DESC_VN='Nhãn số seri khách hàng' Where Program='Barcode Center' and FUNCTION = 'Customer SN Label';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhãn', FUN_VN='Nhãn nhập kho', FUN_DESC_VN='Nhãn nhập kho' Where Program='Barcode Center' and FUNCTION = 'WMS Stock Label';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhãn', FUN_VN='Nhãn thùng', FUN_DESC_VN='Nhãn thùng' Where Program='Barcode Center' and FUNCTION = 'Carton Label';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhãn', FUN_VN='Nhãn lô sản xuất', FUN_DESC_VN='Nhãn lô sản xuất' Where Program='Barcode Center' and FUNCTION = 'Run Card Label';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhãn', FUN_VN='Nhãn pallet', FUN_DESC_VN='Nhãn pallet' Where Program='Barcode Center' and FUNCTION = 'Pallet Label';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhãn', FUN_VN='Nhãn bo mạch con', FUN_DESC_VN='Nhãn bo mạch con' Where Program='Barcode Center' and FUNCTION = 'Sub Board Label';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhãn', FUN_VN='Nhãn MAC', FUN_DESC_VN='Nhãn MAC' Where Program='Barcode Center' and FUNCTION = 'MAC Label';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhãn', FUN_VN='Nhãn số lô sản xuất', FUN_DESC_VN='Nhãn số lô sản xuất' Where Program='Barcode Center' and FUNCTION = 'Rc No Label';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhãn', FUN_VN='Nhãn hộp giấy', FUN_DESC_VN='Nhãn hộp giấy' Where Program='Barcode Center' and FUNCTION = 'Box Label';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhãn', FUN_VN='In lại nhãn', FUN_DESC_VN='In lại nhãn' Where Program='Barcode Center' and FUNCTION = 'Reprint Label';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhãn', FUN_VN='Nhãn số seri lệnh con', FUN_DESC_VN='Nhãn số seri lệnh con' Where Program='Barcode Center' and FUNCTION = 'Sub WO S/N Label';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhãn', FUN_VN='Tách nhãn vật tư', FUN_DESC_VN='Tách nhãn vật tư' Where Program='Barcode Center' and FUNCTION = 'MATERIAL_LABLE_SPLIT';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quy tắc mã hóa', FUN_VN='Định nghĩa quy tắc số seri', FUN_DESC_VN='Định nghĩa quy tắc số seri' Where Program='Barcode Center' and FUNCTION = 'SN Rule Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quy tắc mã hóa', FUN_VN='Định nghĩa quy tắc nhãn nhập kho WMS', FUN_DESC_VN='Định nghĩa quy tắc nhãn nhập kho WMS' Where Program='Barcode Center' and FUNCTION = 'WMS Stock Rule Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quy tắc mã hóa', FUN_VN='Định nghĩa quy tắc số seri khách hàng', FUN_DESC_VN='Định nghĩa quy tắc số seri khách hàng' Where Program='Barcode Center' and FUNCTION = 'Customer SN Rule Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quy tắc mã hóa', FUN_VN='Định nghĩa quy tắc mã thùng', FUN_DESC_VN='Định nghĩa quy tắc mã thùng' Where Program='Barcode Center' and FUNCTION = 'Carton No Rule Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quy tắc mã hóa', FUN_VN='Định nghĩa quy tắc mã pallet', FUN_DESC_VN='Định nghĩa quy tắc mã pallet' Where Program='Barcode Center' and FUNCTION = 'Pallet No Rule Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quy tắc mã hóa', FUN_VN='Định nghĩa quy tắc MAC', FUN_DESC_VN='Định nghĩa quy tắc MAC' Where Program='Barcode Center' and FUNCTION = 'MAC Rule Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quy tắc mã hóa', FUN_VN='Định nghĩa quy tắc mã hộp giấy', FUN_DESC_VN='Định nghĩa quy tắc mã hộp giấy' Where Program='Barcode Center' and FUNCTION = 'Box No Rule Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quy tắc mã hóa', FUN_VN='Định nghĩa quy tắc số seri bo mạch con', FUN_DESC_VN='Định nghĩa quy tắc số seri bo mạch con' Where Program='Barcode Center' and FUNCTION = 'Sub Board Rule Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quy tắc mã hóa', FUN_VN='Định nghĩa quy tắc số lô sản xuất', FUN_DESC_VN='Định nghĩa quy tắc số lô sản xuất' Where Program='Barcode Center' and FUNCTION = 'RC Rule Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quy tắc mã hóa', FUN_VN='Quy tắc mã hóa phương tiện', FUN_DESC_VN='Quy tắc mã hóa phương tiện' Where Program='Barcode Center' and FUNCTION = 'Carrier Rule Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Ràng buộc', FUN_VN='Ràng buộc số bo mạch con', FUN_DESC_VN='Ràng buộc số bo mạch con' Where Program='Barcode Center' and FUNCTION = 'BC SN Sub Mapping';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thu hồi', FUN_VN='Thu hồi số seri', FUN_DESC_VN='Thu hồi số seri' Where Program='Barcode Center' and FUNCTION = 'Cancel Serial Number';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thu hồi', FUN_VN='Thu hồi số seri khách hàng', FUN_DESC_VN='Thu hồi số seri khách hàng' Where Program='Barcode Center' and FUNCTION = 'Cancel Customer SN';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thu hồi', FUN_VN='Thu hồi MAC', FUN_DESC_VN='Thu hồi MAC' Where Program='Barcode Center' and FUNCTION = 'Cancel MAC';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thu hồi', FUN_VN='Thu hồi số bo mạch con', FUN_DESC_VN='Thu hồi số bo mạch con' Where Program='Barcode Center' and FUNCTION = 'Cancel Sub Board';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập kiến trúc thiết bị', FUN_VN='Định nghĩa máy chủ', FUN_DESC_VN='Định nghĩa máy chủ' Where Program='TGSSetup' and FUNCTION = 'Server Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập kiến trúc thiết bị', FUN_VN='Định nghĩa gateway', FUN_DESC_VN='Định nghĩa gateway' Where Program='TGSSetup' and FUNCTION = 'Gateway Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập công việc', FUN_VN='Định nghĩa loại công việc', FUN_DESC_VN='Định nghĩa loại công việc' Where Program='TGSSetup' and FUNCTION = 'Job Type Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập công việc', FUN_VN='Định nghĩa công việc', FUN_DESC_VN='Định nghĩa công việc' Where Program='TGSSetup' and FUNCTION = 'Job Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập công việc', FUN_VN='Định nghĩa hành vi công việc', FUN_DESC_VN='Định nghĩa hành vi công việc' Where Program='TGSSetup' and FUNCTION = 'Job Group Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập loại công việc', FUN_VN='Quản lý báo cáo', FUN_DESC_VN='Quản lý báo cáo' Where Program='TGSSetup' and FUNCTION = 'Report Control';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Hành vi trạm làm việc', FUN_VN='Định nghĩa hành vi trạm làm việc', FUN_DESC_VN='Định nghĩa hành vi trạm làm việc' Where Program='TGSSetup' and FUNCTION = 'Terminal Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập', FUN_VN='Cấu hình', FUN_DESC_VN='Cấu hình' Where Program='Repair' and FUNCTION = 'Configuration';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Sửa chữa', FUN_VN='Thực hiện', FUN_DESC_VN='Thực hiện' Where Program='Repair' and FUNCTION = 'Execution';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Sửa chữa', FUN_VN='Sửa chữa bảng mạch lớn', FUN_DESC_VN='Sửa chữa bảng mạch lớn' Where Program='Repair' and FUNCTION = 'Repair for Panel';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Sửa chữa', FUN_VN='Mã sửa chữa', FUN_DESC_VN='Mã sửa chữa' Where Program='Repair' and FUNCTION = 'Repair Code';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Làm lại', FUN_VN='Thực hiện', FUN_DESC_VN='Thực hiện' Where Program='Rework' and FUNCTION = 'Execution';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Phục hồi', FUN_VN='Phục hồi', FUN_DESC_VN='Phục hồi' Where Program='Rework' and FUNCTION = 'Recover';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Gỡ bỏ linh kiện', FUN_VN='Gỡ bỏ linh kiện quan trọng', FUN_DESC_VN='Gỡ bỏ linh kiện quan trọng' Where Program='Rework' and FUNCTION = 'Remove Key Parts';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Gỡ bỏ linh kiện', FUN_VN='Gỡ bỏ linh kiện theo lệnh sản xuất', FUN_DESC_VN='Gỡ bỏ linh kiện theo lệnh sản xuất' Where Program='Rework' and FUNCTION = 'Remove Key Parts by WO';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập', FUN_VN='Thiết lập phiếu gửi kiểm tra', FUN_DESC_VN='Thiết lập phiếu gửi kiểm tra' Where Program='Quality Control' and FUNCTION = 'CreateInspectionCfg';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập', FUN_VN='Cấu hình', FUN_DESC_VN='Cấu hình' Where Program='Quality Control' and FUNCTION = 'Configuration';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Lấy mẫu', FUN_VN='Tạo phiếu gửi kiểm tra', FUN_DESC_VN='Tạo phiếu gửi kiểm tra' Where Program='Quality Control' and FUNCTION = 'CreateInspection';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Lấy mẫu', FUN_VN='Thực hiện', FUN_DESC_VN='Thực hiện' Where Program='Quality Control' and FUNCTION = 'Execution';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Lấy mẫu', FUN_VN='Xóa số lô', FUN_DESC_VN='Xóa số lô' Where Program='Quality Control' and FUNCTION = 'Drop Lot No';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Lấy mẫu', FUN_VN='IPQC', FUN_DESC_VN='IPQC' Where Program='Quality Control' and FUNCTION = 'IPQC';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập', FUN_VN='Cấu hình', FUN_DESC_VN='Cấu hình' Where Program='Packing' and FUNCTION = 'Configuration';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Đóng gói', FUN_VN='Thực hiện', FUN_DESC_VN='Thực hiện' Where Program='Packing' and FUNCTION = 'Execution';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Đóng gói', FUN_VN='Đóng pallet (thùng)', FUN_DESC_VN='Đóng pallet (thùng)' Where Program='Packing' and FUNCTION = 'Close Pallet(Carton)';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='In lại', FUN_VN='In lại', FUN_DESC_VN='In lại' Where Program='Packing' and FUNCTION = 'Reprint';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập', FUN_VN='Định nghĩa loại báo cáo', FUN_DESC_VN='Định nghĩa loại báo cáo' Where Program='Query' and FUNCTION = 'Report Type Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập', FUN_VN='Cấu hình', FUN_DESC_VN='Cấu hình' Where Program='Query' and FUNCTION = 'Configuration';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Tra cứu', FUN_VN='Lịch sử lô sản xuất', FUN_DESC_VN='Lịch sử lô sản xuất' Where Program='Query' and FUNCTION = 'Travel Card';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Tra cứu', FUN_VN='Lịch sử số seri sản xuất', FUN_DESC_VN='Lịch sử số seri sản xuất' Where Program='Query' and FUNCTION = 'PCS Travel Card';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Phân tích log kiểm thử sản phẩm', FUN_VN='Phân tích log kiểm thử sản phẩm', FUN_DESC_VN='Phân tích log kiểm thử sản phẩm' Where Program='Product Test Transfer' and FUNCTION = 'Product Log Analysis';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập', FUN_VN='Hạng mục kiểm tra nguyên vật liệu đầu vào', FUN_DESC_VN='Hạng mục kiểm tra nguyên vật liệu đầu vào' Where Program='IQC' and FUNCTION = 'IQC Test Item';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Duy trì phiếu RT', FUN_VN='Duy trì phiếu RT', FUN_DESC_VN='Duy trì phiếu RT' Where Program='IQC' and FUNCTION = 'RT Maintain';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thao tác IQC', FUN_VN='Kiểm tra IQC theo lô', FUN_DESC_VN='Kiểm tra IQC theo lô' Where Program='IQC' and FUNCTION = 'IQC By Lot';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thao tác IQC', FUN_VN='IQC bỏ qua hàng loạt', FUN_DESC_VN='IQC bỏ qua hàng loạt' Where Program='IQC' and FUNCTION = 'IQC By Pass';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Lắp ráp', FUN_VN='Cấu hình', FUN_DESC_VN='Cấu hình' Where Program='Assembly' and FUNCTION = 'Configuration';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Lắp ráp', FUN_VN='Nhập liệu lắp ráp', FUN_DESC_VN='Nhập liệu lắp ráp' Where Program='Assembly' and FUNCTION = 'AssemblyInput';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nạp liệu & đưa vào', FUN_VN='Nạp liệu & đưa vào', FUN_DESC_VN='Nạp liệu & đưa vào' Where Program='DIP' and FUNCTION = 'DIP Input';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý hàn paste', FUN_VN='Thiết lập hàn paste', FUN_DESC_VN='Thiết lập hàn paste' Where Program='SMT Auxiliary Material' and FUNCTION = 'Solder Setup';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý hàn paste', FUN_VN='Đông lạnh hàn paste', FUN_DESC_VN='Đông lạnh hàn paste' Where Program='SMT Auxiliary Material' and FUNCTION = 'Solder Freeze';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý hàn paste', FUN_VN='Ủ hàn paste', FUN_DESC_VN='Ủ hàn paste' Where Program='SMT Auxiliary Material' and FUNCTION = 'Solder Wait';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý hàn paste', FUN_VN='Trộn hàn paste', FUN_DESC_VN='Trộn hàn paste' Where Program='SMT Auxiliary Material' and FUNCTION = 'Solder Mix';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý hàn paste', FUN_VN='Mở nắp hàn paste', FUN_DESC_VN='Mở nắp hàn paste' Where Program='SMT Auxiliary Material' and FUNCTION = 'Solder Open';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý hàn paste', FUN_VN='Sử dụng hàn paste', FUN_DESC_VN='Sử dụng hàn paste' Where Program='SMT Auxiliary Material' and FUNCTION = 'Solder Use';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý hàn paste', FUN_VN='Kết thúc sử dụng hàn paste', FUN_DESC_VN='Kết thúc sử dụng hàn paste' Where Program='SMT Auxiliary Material' and FUNCTION = 'Solder Terminate';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý hàn paste', FUN_VN='Tái đông lạnh hàn paste', FUN_DESC_VN='Tái đông lạnh hàn paste' Where Program='SMT Auxiliary Material' and FUNCTION = 'Solder Re-freeze';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý hàn paste', FUN_VN='Phế liệu hàn paste', FUN_DESC_VN='Phế liệu hàn paste' Where Program='SMT Auxiliary Material' and FUNCTION = 'Solder Scrap';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Stencil / Lưỡi gạt', FUN_VN='Stencil', FUN_DESC_VN='Stencil' Where Program='SMT Auxiliary Material' and FUNCTION = 'Stencil';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Stencil / Lưỡi gạt', FUN_VN='Lưỡi gạt', FUN_DESC_VN='Lưỡi gạt' Where Program='SMT Auxiliary Material' and FUNCTION = 'Scraper';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Stencil / Lưỡi gạt', FUN_VN='Nhập lực căng stencil', FUN_DESC_VN='Nhập lực căng stencil' Where Program='SMT Auxiliary Material' and FUNCTION = 'Stencil Tension Input';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Stencil / Lưỡi gạt', FUN_VN='Vệ sinh stencil/lưỡi gạt', FUN_DESC_VN='Vệ sinh stencil/lưỡi gạt' Where Program='SMT Auxiliary Material' and FUNCTION = 'Stencil/Scraper Clean';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Stencil / Lưỡi gạt', FUN_VN='Phế liệu stencil/lưỡi gạt', FUN_DESC_VN='Phế liệu stencil/lưỡi gạt' Where Program='SMT Auxiliary Material' and FUNCTION = 'Stencil/Scraper Scrap';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý MSD', FUN_VN='Mở rộng mã vật liệu MSD', FUN_DESC_VN='Mở rộng mã vật liệu MSD' Where Program='SMT Auxiliary Material' and FUNCTION = 'Part Extend';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý MSD', FUN_VN='Thiết lập thời gian theo cấp MSD', FUN_DESC_VN='Thiết lập thời gian theo cấp MSD' Where Program='SMT Auxiliary Material' and FUNCTION = 'MSD Level Time';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý MSD', FUN_VN='Nhập lò sấy MSD', FUN_DESC_VN='Nhập lò sấy MSD' Where Program='SMT Auxiliary Material' and FUNCTION = 'MSD Baking Input';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý MSD', FUN_VN='Xuất lò sấy MSD', FUN_DESC_VN='Xuất lò sấy MSD' Where Program='SMT Auxiliary Material' and FUNCTION = 'MSD Baking Out';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý MSD', FUN_VN='Mở bao bì MSD', FUN_DESC_VN='Mở bao bì MSD' Where Program='SMT Auxiliary Material' and FUNCTION = 'MSD Open';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý MSD', FUN_VN='Đóng gói lại MSD', FUN_DESC_VN='Đóng gói lại MSD' Where Program='SMT Auxiliary Material' and FUNCTION = 'MSD Close';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết bị', FUN_VN='Kệ vật liệu', FUN_DESC_VN='Kệ vật liệu' Where Program='SMT' and FUNCTION = 'Feeder';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết bị', FUN_VN='Bàn đặt linh kiện', FUN_DESC_VN='Bàn đặt linh kiện' Where Program='SMT' and FUNCTION = 'Table';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết bị', FUN_VN='Xe đẩy', FUN_DESC_VN='Xe đẩy' Where Program='SMT' and FUNCTION = 'Trolley';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhập bảng trạm vật tư', FUN_VN='Nhập bảng trạm vật tư', FUN_DESC_VN='Nhập bảng trạm vật tư' Where Program='SMT' and FUNCTION = 'Import MSL';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhập bảng trạm vật tư', FUN_VN='Truy vấn nhập liệu', FUN_DESC_VN='Truy vấn nhập liệu' Where Program='SMT' and FUNCTION = 'Import Query';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Bảng trạm vật tư theo lệnh', FUN_VN='Tạo bảng trạm vật tư', FUN_DESC_VN='Tạo bảng trạm vật tư' Where Program='SMT' and FUNCTION = 'MSL Setup';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Bảng trạm vật tư theo lệnh', FUN_VN='Duy trì bảng trạm vật tư', FUN_DESC_VN='Duy trì bảng trạm vật tư' Where Program='SMT' and FUNCTION = 'MSL Maintain';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Bảng trạm vật tư theo lệnh', FUN_VN='Chuyển bảng trạm vật tư', FUN_DESC_VN='Chuyển bảng trạm vật tư' Where Program='SMT' and FUNCTION = 'MSL Shared Transfer';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='AOI', FUN_VN='Thiết lập AOI', FUN_DESC_VN='Thiết lập AOI' Where Program='SMT' and FUNCTION = 'AOICfgDll';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='AOI', FUN_VN='Kiểm tra AOI', FUN_DESC_VN='Kiểm tra AOI' Where Program='SMT' and FUNCTION = 'AOI Test';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='VI', FUN_VN='Thiết lập VI', FUN_DESC_VN='Thiết lập VI' Where Program='SMT' and FUNCTION = 'VI Config';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='VI', FUN_VN='Kiểm tra VI', FUN_DESC_VN='Kiểm tra VI' Where Program='SMT' and FUNCTION = 'VI Test';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Cắt bảng', FUN_VN='Cấu hình cắt bảng', FUN_DESC_VN='Cấu hình cắt bảng' Where Program='SMT' and FUNCTION = 'PanelCutCfg';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Cắt bảng', FUN_VN='Thực hiện cắt bảng', FUN_DESC_VN='Thực hiện cắt bảng' Where Program='SMT' and FUNCTION = 'PanelCut';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhập liệu gia công', FUN_VN='Nhập liệu gia công', FUN_DESC_VN='Nhập liệu gia công' Where Program='SMT' and FUNCTION = 'OutsourceImport';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập cảnh báo', FUN_VN='Nhóm email', FUN_DESC_VN='Nhóm email' Where Program='Alarm' and FUNCTION = 'Mail Group';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập cảnh báo', FUN_VN='Định nghĩa sự kiện 2', FUN_DESC_VN='Định nghĩa sự kiện 2' Where Program='Alarm' and FUNCTION = 'Event Define2';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập cảnh báo', FUN_VN='Định nghĩa sự kiện', FUN_DESC_VN='Định nghĩa sự kiện' Where Program='Alarm' and FUNCTION = 'Event Define';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập cảnh báo', FUN_VN='Cấu hình cảnh báo', FUN_DESC_VN='Cấu hình cảnh báo' Where Program='Alarm' and FUNCTION = 'Alarm Config';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thao tác cảnh báo', FUN_VN='Bắt đầu thủ công', FUN_DESC_VN='Bắt đầu thủ công' Where Program='Alarm' and FUNCTION = 'Manual Start';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thao tác cảnh báo', FUN_VN='Giám sát cảnh báo', FUN_DESC_VN='Giám sát cảnh báo' Where Program='Alarm' and FUNCTION = 'Alarm Monitor';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thao tác cảnh báo', FUN_VN='Thực hiện cảnh báo', FUN_DESC_VN='Thực hiện cảnh báo' Where Program='Alarm' and FUNCTION = 'Alarm Execute';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập', FUN_VN='Đồ gá', FUN_DESC_VN='Đồ gá' Where Program='ToolingManager' and FUNCTION = 'Tooling';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý đồ gá', FUN_VN='Xuất đồ gá', FUN_DESC_VN='Xuất đồ gá' Where Program='ToolingManager' and FUNCTION = 'Tooling Take Out';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý đồ gá', FUN_VN='Trả đồ gá', FUN_DESC_VN='Trả đồ gá' Where Program='ToolingManager' and FUNCTION = 'Tooling Return';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý đồ gá', FUN_VN='Bảo dưỡng đồ gá', FUN_DESC_VN='Bảo dưỡng đồ gá' Where Program='ToolingManager' and FUNCTION = 'Tooling Maintain';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý đồ gá', FUN_VN='Phế liệu đồ gá', FUN_DESC_VN='Phế liệu đồ gá' Where Program='ToolingManager' and FUNCTION = 'Tooling Scrap';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Bảo dưỡng đồ gá', FUN_VN='Định nghĩa hạng mục bảo dưỡng', FUN_DESC_VN='Định nghĩa hạng mục bảo dưỡng' Where Program='ToolingManager' and FUNCTION = 'Tooling Maintain Item';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Bảo dưỡng đồ gá', FUN_VN='Thực hiện bảo dưỡng', FUN_DESC_VN='Thực hiện bảo dưỡng' Where Program='ToolingManager' and FUNCTION = 'Tooling Maintain Execute';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thực hiện', FUN_VN='Lô sản xuất', FUN_DESC_VN='Lô sản xuất' Where Program='WIP' and FUNCTION = 'RC';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thực hiện', FUN_VN='Báo công máy', FUN_DESC_VN='Báo công máy' Where Program='WIP' and FUNCTION = 'RCTravelByMachine';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thực hiện', FUN_VN='Duy trì máy trước', FUN_DESC_VN='Duy trì máy trước' Where Program='WIP' and FUNCTION = 'Pre Machine';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thực hiện', FUN_VN='Hoàn nguyên vào trạm lô sản xuất', FUN_DESC_VN='Hoàn nguyên vào trạm lô sản xuất' Where Program='WIP' and FUNCTION = 'RC Input Reverse';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thực hiện', FUN_VN='Duy trì ràng buộc lô', FUN_DESC_VN='Duy trì ràng buộc lô' Where Program='WIP' and FUNCTION = 'BatchMaintain';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý kho WIP', FUN_VN='Nhập kho WIP', FUN_DESC_VN='Nhập kho WIP' Where Program='WIP' and FUNCTION = 'WIP INV';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý kho WIP', FUN_VN='Quản lý kệ kho WIP', FUN_DESC_VN='Quản lý kệ kho WIP' Where Program='WIP' and FUNCTION = 'WIPINV LOCATION';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý kho WIP', FUN_VN='Nhập kho theo số seri', FUN_DESC_VN='Nhập kho theo số seri' Where Program='WIP' and FUNCTION = 'WIP INV SN';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Duy trì thời gian lao động', FUN_VN='Thời gian lao động không thiết yếu', FUN_DESC_VN='Thời gian lao động không thiết yếu' Where Program='Work Hour' and FUNCTION = 'Idle Time Maintain';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Duy trì thời gian lao động', FUN_VN='Duy trì mở chuyền', FUN_DESC_VN='Duy trì mở chuyền' Where Program='Work Hour' and FUNCTION = 'OP Maintain';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Duy trì thời gian lao động', FUN_VN='Thời gian chuẩn bị', FUN_DESC_VN='Thời gian chuẩn bị' Where Program='Work Hour' and FUNCTION = 'Pre-Machine';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Vào/Ra ca', FUN_VN='Thực hiện', FUN_DESC_VN='Thực hiện' Where Program='Work Hour' and FUNCTION = 'Punch In Out';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Sản xuất hàng loạt', FUN_VN='Quét trạm hàng loạt (kèm thời gian)', FUN_DESC_VN='Quét trạm hàng loạt (kèm thời gian)' Where Program='Work Hour' and FUNCTION = 'Multi SN Pass(WT)';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Sản xuất hàng loạt', FUN_VN='Thiết lập trạm quét hàng loạt (kèm thời gian)', FUN_DESC_VN='Thiết lập trạm quét hàng loạt (kèm thời gian)' Where Program='Work Hour' and FUNCTION = 'Multi SN Pass(WT) Setup';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Báo công thời gian lao động', FUN_VN='Báo công thời gian lao động', FUN_DESC_VN='Báo công thời gian lao động' Where Program='Work Hour' and FUNCTION = 'Work Hour Commit';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập', FUN_VN='Thiết lập', FUN_DESC_VN='Thiết lập' Where Program='Shipping' and FUNCTION = 'ShippingCfgDll';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Xuất hàng', FUN_VN='Duy trì phiếu xuất hàng', FUN_DESC_VN='Duy trì phiếu xuất hàng' Where Program='Shipping' and FUNCTION = 'ShipDNItemDll';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Xuất hàng', FUN_VN='Thực hiện', FUN_DESC_VN='Thực hiện' Where Program='Shipping' and FUNCTION = 'ShippingDll';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Xuất hàng', FUN_VN='Huỷ xuất hàng', FUN_DESC_VN='Huỷ xuất hàng' Where Program='Shipping' and FUNCTION = 'ShippingRollbackDll';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Xuất hàng', FUN_VN='Thêm dữ liệu xuất hàng', FUN_DESC_VN='Thêm dữ liệu xuất hàng' Where Program='Shipping' and FUNCTION = 'ShippingAddInfoDll';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Chuyển dữ liệu số seri cũ', FUN_VN='Chuyển dữ liệu số seri cũ', FUN_DESC_VN='Chuyển dữ liệu số seri cũ' Where Program='Shipping' and FUNCTION = 'TransferSN';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Kệ', FUN_VN='Cấu hình kệ', FUN_DESC_VN='Cấu hình kệ' Where Program='Pick To Light' and FUNCTION = 'CTestShelf';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Kệ', FUN_VN='Tạo phiếu nhập kệ', FUN_DESC_VN='Tạo phiếu nhập kệ' Where Program='Pick To Light' and FUNCTION = 'ShelfUp';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Kệ', FUN_VN='Tạo phiếu xuất kệ', FUN_DESC_VN='Tạo phiếu xuất kệ' Where Program='Pick To Light' and FUNCTION = 'ShelfDown';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Kệ', FUN_VN='Thực hiện phiếu nhập kệ', FUN_DESC_VN='Thực hiện phiếu nhập kệ' Where Program='Pick To Light' and FUNCTION = 'ShelfUpExcute';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Kệ', FUN_VN='Thực hiện phiếu xuất kệ', FUN_DESC_VN='Thực hiện phiếu xuất kệ' Where Program='Pick To Light' and FUNCTION = 'ShelfDownExcute';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Kệ', FUN_VN='Đổi kệ nhanh', FUN_DESC_VN='Đổi kệ nhanh' Where Program='Pick To Light' and FUNCTION = 'FastChangeShelf';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Kệ', FUN_VN='Đối chiếu tồn kho kệ điện tử', FUN_DESC_VN='Đối chiếu tồn kho kệ điện tử' Where Program='Pick To Light' and FUNCTION = 'ShelfStockConfirm';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quyền xử lý nhiệm vụ kệ điện tử', FUN_VN='Quyền xử lý nhiệm vụ kệ điện tử', FUN_DESC_VN='Quyền xử lý nhiệm vụ kệ điện tử' Where Program='Pick To Light' and FUNCTION = 'btnExecute';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý kho', FUN_VN='Vị trí lưu trữ kho', FUN_DESC_VN='Vị trí lưu trữ kho' Where Program='WMS Inventory' and FUNCTION = 'WMS Warehouse';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý nguyên vật liệu', FUN_VN='In nhãn nguyên vật liệu', FUN_DESC_VN='In nhãn nguyên vật liệu' Where Program='WMS Inventory' and FUNCTION = 'InvMaterialdll';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Quản lý nguyên vật liệu', FUN_VN='Nhập kho nguyên vật liệu', FUN_DESC_VN='Nhập kho nguyên vật liệu' Where Program='WMS Inventory' and FUNCTION = 'MaterialIN';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Phiếu lĩnh theo lệnh', FUN_VN='Tạo phiếu lĩnh theo lệnh', FUN_DESC_VN='Tạo phiếu lĩnh theo lệnh' Where Program='WMS Inventory' and FUNCTION = 'WIPIssueRequest';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Phiếu lĩnh theo lệnh', FUN_VN='Trả lại phiếu lĩnh theo lệnh', FUN_DESC_VN='Trả lại phiếu lĩnh theo lệnh' Where Program='WMS Inventory' and FUNCTION = 'WIPReturnRequest';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhập kho theo lệnh', FUN_VN='Phiếu đề nghị nhập kho theo lệnh', FUN_DESC_VN='Phiếu đề nghị nhập kho theo lệnh' Where Program='WMS Inventory' and FUNCTION = 'WOInboundRequest';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nhập kho theo lệnh', FUN_VN='Thực hiện nhập kho theo lệnh', FUN_DESC_VN='Thực hiện nhập kho theo lệnh' Where Program='WMS Inventory' and FUNCTION = 'WOInbound';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Ghép/tách thùng/pallet', FUN_VN='Ghép/tách thùng hoặc pallet', FUN_DESC_VN='Ghép/tách thùng hoặc pallet' Where Program='WMS Inventory' and FUNCTION = 'RePackingPallet';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Ghép/tách thùng/pallet', FUN_VN='Ghép/tách thùng hoặc pallet', FUN_DESC_VN='Ghép/tách thùng hoặc pallet' Where Program='WMS Inventory' and FUNCTION = 'RePackingCarton';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Tạo phiếu nhập kho', FUN_VN='Phiếu thu linh tinh', FUN_DESC_VN='Phiếu thu linh tinh' Where Program='WMS Inventory' and FUNCTION = 'Misc Stock Bill';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Tạo phiếu nhập kho', FUN_VN='Nhập kho linh tinh', FUN_DESC_VN='Nhập kho linh tinh' Where Program='WMS Inventory' and FUNCTION = 'Misc MaterialIN';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Chuyển dữ liệu ReelID cũ', FUN_VN='Chuyển dữ liệu ReelID cũ', FUN_DESC_VN='Chuyển dữ liệu ReelID cũ' Where Program='WMS Inventory' and FUNCTION = 'TransferReelID';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nạp liệu SMT (PDA Android)', FUN_VN='Nạp liệu SMT (PDA Android)', FUN_DESC_VN='Nạp liệu SMT (PDA Android)' Where Program='SMT PDA' and FUNCTION = 'SMT Load(PDA Android)';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Nạp Stencil & Lưỡi gạt', FUN_VN='StencilScraperLoad', FUN_DESC_VN='StencilScraperLoad' Where Program='SMT PDA' and FUNCTION = 'StencilScraperLoad';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='eSOP', FUN_VN='Máy khách SOP', FUN_DESC_VN='Máy khách SOP' Where Program='ICMES' and FUNCTION = 'SOPClient';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập', FUN_VN='Loại phương tiện', FUN_DESC_VN='Loại phương tiện' Where Program='Carrier Manager' and FUNCTION = 'CarrierType';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập', FUN_VN='Tạo phương tiện', FUN_DESC_VN='Tạo phương tiện' Where Program='Carrier Manager' and FUNCTION = 'CarrierCreate';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập', FUN_VN='In phương tiện', FUN_DESC_VN='In phương tiện' Where Program='Carrier Manager' and FUNCTION = 'CarrierLabel';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thiết lập', FUN_VN='Hạn chế phương tiện', FUN_DESC_VN='Hạn chế phương tiện' Where Program='Carrier Manager' and FUNCTION = 'CarrierLimit';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thực hiện', FUN_VN='Gán phương tiện', FUN_DESC_VN='Gán phương tiện' Where Program='Carrier Manager' and FUNCTION = 'CarrierAssign';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thực hiện', FUN_VN='Huỷ gán phương tiện', FUN_DESC_VN='Huỷ gán phương tiện' Where Program='Carrier Manager' and FUNCTION = 'CarrierUnAssign';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thực hiện', FUN_VN='Khoá phương tiện', FUN_DESC_VN='Khoá phương tiện' Where Program='Carrier Manager' and FUNCTION = 'CarrierHold';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thực hiện', FUN_VN='Mở khoá phương tiện', FUN_DESC_VN='Mở khoá phương tiện' Where Program='Carrier Manager' and FUNCTION = 'CarrierRelease';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thực hiện', FUN_VN='Bắt đầu vệ sinh phương tiện', FUN_DESC_VN='Bắt đầu vệ sinh phương tiện' Where Program='Carrier Manager' and FUNCTION = 'Carrier Clean Start';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thực hiện', FUN_VN='Kết thúc vệ sinh phương tiện', FUN_DESC_VN='Kết thúc vệ sinh phương tiện' Where Program='Carrier Manager' and FUNCTION = 'Carrier Clean End';
Update SAJET.SYS_PROGRAM_FUN_NAME SET FUN_TYPE_VN='Thực hiện', FUN_VN='Thay hộp phương tiện', FUN_DESC_VN='Thay hộp phương tiện' Where Program='Carrier Manager' and FUNCTION = 'CarrierChange';


commit;
